import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { lookup } from 'node:dns/promises';
import { isIP } from 'node:net';
const FILE=join(fileURLToPath(new URL('../data/',import.meta.url)),'notification-settings.json');
function load(){try{return existsSync(FILE)?JSON.parse(readFileSync(FILE,'utf8')):{}}catch{return {}}}
function save(db){mkdirSync(dirname(FILE),{recursive:true});writeFileSync(FILE,JSON.stringify(db,null,2))}
const db=load();
function privateIp(ip){if(!ip)return true;if(ip.includes(':')){const x=ip.toLowerCase();return x==='::1'||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe8')||x.startsWith('fe9')||x.startsWith('fea')||x.startsWith('feb')||x.startsWith('::ffff:127.')||x.startsWith('::ffff:10.')||x.startsWith('::ffff:192.168.');}return /^127\.|^10\.|^192\.168\.|^169\.254\.|^0\.|^172\.(1[6-9]|2\d|3[01])\./.test(ip)}
export async function validateWebhookUrl(value){const u=new URL(String(value||'').trim());if(u.protocol!=='https:')throw new Error('Webhook URL must use HTTPS.');if(u.username||u.password)throw new Error('Webhook URL cannot contain credentials.');if(['localhost','localhost.localdomain'].includes(u.hostname.toLowerCase())||u.hostname.endsWith('.local'))throw new Error('Private/local webhook destinations are not allowed.');if(isIP(u.hostname)&&privateIp(u.hostname))throw new Error('Private/local webhook destinations are not allowed.');const addresses=await lookup(u.hostname,{all:true});if(!addresses.length||addresses.some(x=>privateIp(x.address)))throw new Error('Webhook destination resolves to a private/local address.');return u.toString()}
export function getNotificationSettings(origin){const x=db[origin];if(!x)return null;return {...x,secret:x.secret?'••••••••':null}}
export async function setNotificationSettings(origin,opts={}){const prev=db[origin]||{};let webhookUrl=String(opts.webhookUrl||'').trim();if(webhookUrl)webhookUrl=await validateWebhookUrl(webhookUrl);const now=new Date().toISOString();db[origin]={origin,enabled:opts.enabled===true&&!!webhookUrl,webhookUrl,secret:opts.secret===undefined?prev.secret||'':String(opts.secret||'').slice(0,200),notifyResolved:opts.notifyResolved!==false,createdAt:prev.createdAt||now,updatedAt:now,lastDeliveryAt:prev.lastDeliveryAt||null,lastDeliveryStatus:prev.lastDeliveryStatus||null,lastDeliveryError:prev.lastDeliveryError||null};save(db);return getNotificationSettings(origin)}
export async function deliverWebhook(origin,event,{test=false}={}){const cfg=db[origin];if(!cfg?.enabled||!cfg.webhookUrl)return {skipped:true};await validateWebhookUrl(cfg.webhookUrl);const payload={source:'WebDoctor',version:'3.8.0',test,website:origin,event:{id:event.id||null,type:event.type||'test',severity:event.severity||'info',state:event.state||'new',title:event.title||'WebDoctor test notification',message:event.message||'Webhook delivery is configured correctly.',createdAt:event.createdAt||new Date().toISOString(),result:event.result||null}};const headers={'content-type':'application/json','user-agent':'WebDoctor/3.8'};if(cfg.secret)headers['x-webdoctor-secret']=cfg.secret;try{const r=await fetch(cfg.webhookUrl,{method:'POST',headers,body:JSON.stringify(payload),redirect:'error',signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`Webhook returned HTTP ${r.status}`);cfg.lastDeliveryAt=new Date().toISOString();cfg.lastDeliveryStatus='delivered';cfg.lastDeliveryError=null;save(db);return {delivered:true,status:r.status}}catch(e){cfg.lastDeliveryAt=new Date().toISOString();cfg.lastDeliveryStatus='failed';cfg.lastDeliveryError=String(e.message||e).slice(0,300);save(db);return {delivered:false,error:cfg.lastDeliveryError}}
}
export async function deliverMonitoringEvents(origin,events=[]){const cfg=db[origin];if(!cfg?.enabled)return [];const sendable=events.filter(e=>(e.state==='new'&&e.type!=='check')||(cfg.notifyResolved&&e.state==='resolved'));const results=[];for(const e of sendable)results.push({eventId:e.id,...await deliverWebhook(origin,e)});return results}
