import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { lookup } from 'node:dns/promises';
import { isIP } from 'node:net';
import nodemailer from 'nodemailer';
const FILE=join(fileURLToPath(new URL('../data/',import.meta.url)),'notification-settings.json');
function load(){try{return existsSync(FILE)?JSON.parse(readFileSync(FILE,'utf8')):{}}catch{return {}}}
function save(db){mkdirSync(dirname(FILE),{recursive:true});writeFileSync(FILE,JSON.stringify(db,null,2))}
const db=load();
function privateIp(ip){if(!ip)return true;if(ip.includes(':')){const x=ip.toLowerCase();return x==='::1'||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe8')||x.startsWith('fe9')||x.startsWith('fea')||x.startsWith('feb')||x.startsWith('::ffff:127.')||x.startsWith('::ffff:10.')||x.startsWith('::ffff:192.168.');}return /^127\.|^10\.|^192\.168\.|^169\.254\.|^0\.|^172\.(1[6-9]|2\d|3[01])\./.test(ip)}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim())}
export async function validateWebhookUrl(value){const u=new URL(String(value||'').trim());if(u.protocol!=='https:')throw new Error('Webhook URL must use HTTPS.');if(u.username||u.password)throw new Error('Webhook URL cannot contain credentials.');if(['localhost','localhost.localdomain'].includes(u.hostname.toLowerCase())||u.hostname.endsWith('.local'))throw new Error('Private/local webhook destinations are not allowed.');if(isIP(u.hostname)&&privateIp(u.hostname))throw new Error('Private/local webhook destinations are not allowed.');const addresses=await lookup(u.hostname,{all:true});if(!addresses.length||addresses.some(x=>privateIp(x.address)))throw new Error('Webhook destination resolves to a private/local address.');return u.toString()}
function publicSettings(x){if(!x)return null;return {...x,secret:x.secret?'••••••••':null,smtpPass:x.smtpPass?'••••••••':null}}
export function getNotificationSettings(origin){return publicSettings(db[origin])}
export async function setNotificationSettings(origin,opts={}){const prev=db[origin]||{};let webhookUrl=String(opts.webhookUrl??prev.webhookUrl??'').trim();if(webhookUrl)webhookUrl=await validateWebhookUrl(webhookUrl);const email=String(opts.email??prev.email??'').trim();const smtpHost=String(opts.smtpHost??prev.smtpHost??'').trim();const smtpPort=Math.max(1,Math.min(65535,Number(opts.smtpPort??prev.smtpPort??587)||587));const smtpUser=String(opts.smtpUser??prev.smtpUser??'').trim();const fromEmail=String(opts.fromEmail??prev.fromEmail??smtpUser??'').trim();if(opts.emailEnabled===true){if(!validEmail(email))throw new Error('Enter a valid notification email address.');if(!smtpHost)throw new Error('SMTP host is required for email notifications.');if(!smtpUser)throw new Error('SMTP username is required for email notifications.');if(!prev.smtpPass&&!opts.smtpPass)throw new Error('SMTP password or app password is required.');if(fromEmail&&!validEmail(fromEmail))throw new Error('Enter a valid From email address.');}
 const now=new Date().toISOString();db[origin]={origin,
  emailEnabled:opts.emailEnabled===true,email,emailNotifyResolved:opts.emailNotifyResolved!==false,smtpHost,smtpPort,smtpSecure:opts.smtpSecure===true,smtpUser,fromEmail,smtpPass:opts.smtpPass===undefined?prev.smtpPass||'':String(opts.smtpPass||'').slice(0,500),
  enabled:opts.enabled===true&&!!webhookUrl,webhookUrl,secret:opts.secret===undefined?prev.secret||'':String(opts.secret||'').slice(0,200),notifyResolved:opts.notifyResolved!==false,
  createdAt:prev.createdAt||now,updatedAt:now,lastDeliveryAt:prev.lastDeliveryAt||null,lastDeliveryStatus:prev.lastDeliveryStatus||null,lastDeliveryError:prev.lastDeliveryError||null,lastEmailAt:prev.lastEmailAt||null,lastEmailStatus:prev.lastEmailStatus||null,lastEmailError:prev.lastEmailError||null};save(db);return getNotificationSettings(origin)}
function payload(origin,event,test=false){return {source:'WebDoctor',version:'3.9.0',test,website:origin,event:{id:event.id||null,type:event.type||'test',severity:event.severity||'info',state:event.state||'new',title:event.title||'WebDoctor test notification',message:event.message||'Notification delivery is configured correctly.',createdAt:event.createdAt||new Date().toISOString(),result:event.result||null}}}
export async function deliverWebhook(origin,event,{test=false}={}){const cfg=db[origin];if(!cfg?.enabled||!cfg.webhookUrl)return {skipped:true};await validateWebhookUrl(cfg.webhookUrl);const body=payload(origin,event,test);const headers={'content-type':'application/json','user-agent':'WebDoctor/3.9'};if(cfg.secret)headers['x-webdoctor-secret']=cfg.secret;try{const r=await fetch(cfg.webhookUrl,{method:'POST',headers,body:JSON.stringify(body),redirect:'error',signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`Webhook returned HTTP ${r.status}`);cfg.lastDeliveryAt=new Date().toISOString();cfg.lastDeliveryStatus='delivered';cfg.lastDeliveryError=null;save(db);return {delivered:true,status:r.status}}catch(e){cfg.lastDeliveryAt=new Date().toISOString();cfg.lastDeliveryStatus='failed';cfg.lastDeliveryError=String(e.message||e).slice(0,300);save(db);return {delivered:false,error:cfg.lastDeliveryError}}}
export async function deliverEmail(origin,event,{test=false}={}){const cfg=db[origin];if(!cfg?.emailEnabled)return {skipped:true};if(!cfg.smtpHost||!cfg.smtpUser||!cfg.smtpPass||!validEmail(cfg.email))return {skipped:true,error:'Email settings are incomplete.'};const p=payload(origin,event,test);try{const transport=nodemailer.createTransport({host:cfg.smtpHost,port:cfg.smtpPort||587,secure:cfg.smtpSecure===true,auth:{user:cfg.smtpUser,pass:cfg.smtpPass},connectionTimeout:10000,greetingTimeout:10000,socketTimeout:15000});const severity=String(p.event.severity||'info').toUpperCase();await transport.sendMail({from:cfg.fromEmail||cfg.smtpUser,to:cfg.email,subject:`[WebDoctor ${severity}] ${p.event.title} — ${origin}`,text:`${p.event.title}\n\n${p.event.message}\n\nWebsite: ${origin}\nState: ${p.event.state}\nSeverity: ${severity}\nHealth: ${p.event.result?.score??'—'}/100\nTime: ${p.event.createdAt}\n\nSent by WebDoctor v3.9${test?' (test)':''}.`});cfg.lastEmailAt=new Date().toISOString();cfg.lastEmailStatus='delivered';cfg.lastEmailError=null;save(db);return {delivered:true}}catch(e){cfg.lastEmailAt=new Date().toISOString();cfg.lastEmailStatus='failed';cfg.lastEmailError=String(e.message||e).slice(0,300);save(db);return {delivered:false,error:cfg.lastEmailError}}}
export async function deliverMonitoringEvents(origin,events=[]){const cfg=db[origin];if(!cfg)return [];const results=[];for(const e of events){if(e.type==='check')continue;if(e.state==='new'){if(cfg.emailEnabled)results.push({channel:'email',eventId:e.id,...await deliverEmail(origin,e)});if(cfg.enabled)results.push({channel:'webhook',eventId:e.id,...await deliverWebhook(origin,e)})}else if(e.state==='resolved'){if(cfg.emailEnabled&&cfg.emailNotifyResolved!==false)results.push({channel:'email',eventId:e.id,...await deliverEmail(origin,e)});if(cfg.enabled&&cfg.notifyResolved!==false)results.push({channel:'webhook',eventId:e.id,...await deliverWebhook(origin,e)})}}return results}
