const url=()=>String(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const key=()=>process.env.SUPABASE_SERVICE_ROLE_KEY||'';
export function durableStoreEnabled(){return Boolean(url()&&key())}
async function request(path,{method='GET',body,prefer='return=representation'}={}){if(!durableStoreEnabled())throw new Error('Supabase persistence is not configured.');const r=await fetch(`${url()}/rest/v1/${path}`,{method,headers:{apikey:key(),authorization:`Bearer ${key()}`,'content-type':'application/json',prefer},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(10000)});const text=await r.text();if(!r.ok)throw new Error(`Supabase persistence failed (${r.status}): ${text.slice(0,300)}`);return text?JSON.parse(text):[]}
const q=s=>encodeURIComponent(s);
export async function saveScan(report){const origin=new URL(report.target).origin;await request('webdoctor_scans',{method:'POST',body:{origin,created_at:report.scannedAt||new Date().toISOString(),report}})}
export async function scanHistory(origin,limit=20){const o=new URL(origin).origin;const rows=await request(`webdoctor_scans?origin=eq.${q(o)}&select=report,created_at&order=created_at.desc&limit=${limit}`);return rows.map(x=>({...x.report,createdAt:x.created_at}))}
export async function regression(origin){const h=await scanHistory(origin,2);if(h.length<2)return{available:false};const [current,previous]=h,keyOf=x=>`${x.title}|${x.url||''}`,c=new Map((current.issues||[]).map(x=>[keyOf(x),x])),p=new Map((previous.issues||[]).map(x=>[keyOf(x),x]));return{available:true,current,previous,scoreDelta:(current.summary?.score||0)-(previous.summary?.score||0),fixed:[...p].filter(([k])=>!c.has(k)).map(([,v])=>v),newIssues:[...c].filter(([k])=>!p.has(k)).map(([,v])=>v),unchanged:[...c].filter(([k])=>p.has(k)).map(([,v])=>v)}}
export async function saveCapacity(origin,result){origin=new URL(origin).origin;await request('webdoctor_capacity_history',{method:'POST',body:{origin,created_at:new Date().toISOString(),result}})}
export async function capacityHistory(origin,limit=12){const o=new URL(origin).origin;const rows=await request(`webdoctor_capacity_history?origin=eq.${q(o)}&select=result,created_at&order=created_at.desc&limit=${limit}`);return rows.map(x=>({...x.result,createdAt:x.created_at}))}
export async function saveMonitor(origin,config){origin=new URL(origin).origin;await request('webdoctor_monitors?on_conflict=origin',{method:'POST',body:{origin,config,updated_at:new Date().toISOString()},prefer:'resolution=merge-duplicates,return=representation'});return config}
export async function getMonitor(origin){origin=new URL(origin).origin;const rows=await request(`webdoctor_monitors?origin=eq.${q(origin)}&select=config&limit=1`);return rows[0]?.config||null}
export async function addEvent(origin,event){origin=new URL(origin).origin;const rows=await request('webdoctor_monitoring_events',{method:'POST',body:{origin,created_at:event.createdAt||new Date().toISOString(),event,is_read:false}});return rows[0]||null}
export async function monitoringEvents(origin,limit=100){origin=new URL(origin).origin;const rows=await request(`webdoctor_monitoring_events?origin=eq.${q(origin)}&select=id,event,created_at,is_read&order=created_at.desc&limit=${limit}`);return rows.map(x=>({...x.event,id:x.id,createdAt:x.created_at,isRead:x.is_read}))}
export async function markEventsRead(origin){origin=new URL(origin).origin;await request(`webdoctor_monitoring_events?origin=eq.${q(origin)}&is_read=eq.false`,{method:'PATCH',body:{is_read:true}})}
export async function saveProject(origin,{verificationMethod='Website proof'}={}){origin=new URL(origin).origin;await request('webdoctor_projects?on_conflict=origin',{method:'POST',body:{origin,verification_method:verificationMethod,verified_at:new Date().toISOString(),updated_at:new Date().toISOString()},prefer:'resolution=merge-duplicates,return=representation'})}
export async function projects(){return request('webdoctor_projects?select=origin,verification_method,verified_at,updated_at&order=updated_at.desc')}
